### ISSUE TITLE
蓝牙鼠标不记录和保存，每次需要重新配对（个例）

### ISSUE THREAD

**Issue by JeredXu** [ske1996/matebook-13and14-OpenCore-Hackintosh#130]
**Device info（设备信息）**

Matebook 13 2019  

CPU:  i5
RAM:  8g
SSD:WD
MacOS version:   11.1
EFI version:20210130

**Describe the bug（问题简述）**

看介绍支持微软设计师鼠标，于是购买了，可以连上，但是每次休眠后或者重启后，都需要重新配对，包括鼠标也需要重新调成配对模式，重新连接。
但蓝牙耳机不会，重启后也记录了，可以点一下就连接。
对比发现，连接上后鼠标和蓝牙设备连接的显示不同，虽然都可以使用，但是鼠标的是灰色，耳机是白色。

**To Reproduce（详述问题发生前的操作）**
无

**Screenshots（截图）**
<img width="749" alt="截屏2021-02-08 下午10 32 02" src="https://user-images.githubusercontent.com/78747239/107244947-9216a500-6a69-11eb-9868-b03f3b316f6d.png">

**Additional context（其他附件事项）**

**Comment by ske1996** [comment]
不好意思啊，这个问题我还真不会解决……我从不用蓝牙鼠标……
那个鼠标是别人测试出来给我的结果

**Comment by ske1996** [comment]
虽然我知道只有在切换过系统并连过鼠标后才需要重新配对，但是你提到了睡眠，我就有点懵了

**Comment by JeredXu** [comment]
> 虽然我知道只有在切换过系统并连过鼠标后才需要重新配对，但是你提到了睡眠，我就有点懵了

谢谢你，可能我描述错误，就是每次关闭盖子再打开，都需要重新配对连接。可能这个蓝牙驱动还是不太适配吧，感谢回复！

**Comment by ske1996** [comment]
虽然我这么说可能有些天才吧的味道……

要不清空一下nvram试试？

哈哈哈

**Comment by JeredXu** [comment]
试过了，还不行，干脆重新买鼠标去了，看淘宝的某款飞利浦鼠标也支持Mac,买来试试

**Comment by JeredXu** [comment]
不过要说，其他都完美，包括摄像头。

就是每次Wi-Fi切换的时候都要续租dhcp有点麻烦

**Comment by ske1996** [comment]
> 试过了，还不行，干脆重新买鼠标去了，看淘宝的某款飞利浦鼠标也支持Mac,买来试试

没，支不支持macos并不是蓝牙鼠标能不能用的重点，这个不用纠结了

我又在老位置贴了几个鼠标，你可以试试

**Comment by JeredXu** [comment]
read的那篇吗？没有看到鼠标推荐啊，我新买的这个测试了可以，现在关机重启也可以自动连接鼠标了，偶尔鼠标断开连接，我在继续使用测试。鼠标型号飞利浦SPK7355充电款

**Comment by ske1996** [comment]
蓝牙详情里
