### ISSUE TITLE
MateBook14 2019运行macOS Big Sur状态良好

### ISSUE THREAD

**Issue by Chin-Me** [ske1996/matebook-13and14-OpenCore-Hackintosh#157]
Matebook 14 2019 
CPU:intel Core i7-8565U
RAM:8GB
SSD:WDC PC SN720 SDAPNTW-512G-1127
macOS Version：macOS Big Sur 11.0.1 (20B29)
Works fine:
蓝牙,Wi-Fi,睡眠,触控板,CPU变频等都工作正常
Doesnt work:
硬件方面还是MX250,指纹和摄像头这三样用不了,软件方面iMessage无法正常使用,但是三码已经改过了,iCloud、App Store和FaceTime好像都没有什么异常,FaceTime只是因为没有摄像头黑的,就是iMessage不知道为什么不能用...
具体表现是
如果设置中没有登录iCloud:输入Apple ID及密码-双重认证-转圈-发生了未知错误
设置当中登录了iCloud:打开iMessage要求输入Apple ID及密码-转圈-疑似登录成功-过了几秒后又重新注销,弹出登录界面.就一直这样循环
这个在黑苹果当中好像不是个例,在其它配置的EFI issues中也见过一个,已经向Apple Support确认我的Apple ID激活了iMessage,iPhone上也可以正常发送

**Comment by ske1996** [comment]
三码改过≠就一定okay

你改的三码肯定没去校验可用性

多的不说了，自己百度

**Comment by Chin-Me** [comment]
> 三码改过≠就一定okay
> 
> 你改的三码肯定没去校验可用性
> 
> 你的三码没弄好≠是黑苹果的通病。是你自己的问题
> 
> 多的不说了，自己百度

我百度得到的只有检验序列号有效,我的序列号在官网那边是无效的,百度上基本上就这么几个环节了,其它的还请指教

**Comment by ske1996** [comment]
设有个黑苹果用户A，roll了三码为AAAAAAA，并官网校验为未激活设备，然后就开开心心的用了。
然后又有个黑苹果用户B，roll了三码碰巧roll出来的也是AAAAAAA，并官网校验为未激活设备，然后也开开心心的用了。
那么B的apple service就会被block。就算你校验了，到那时roll出了别人正在用的。这也有可能，尽管概率不大。

log out你的id。重roll一下四码。reset nvram。之后再osx里Factory reset。
我认为上述为缺一不可。

**Comment by Chin-Me** [comment]
> 设有个黑苹果用户A，roll了三码为AAAAAAA，并官网校验为未激活设备，然后就开开心心的用了。
> 然后又有个黑苹果用户B，roll了三码碰巧roll出来的也是AAAAAAA，并官网校验为未激活设备，然后也开开心心的用了。
> 那么B的apple service就会被block。就算你校验了，到那时roll出了别人正在用的。这也有可能，尽管概率不大。
> 
> log out你的id。重roll一下四码。reset nvram。之后再osx里Factory reset。
> 我认为上述为缺一不可。

好的,我先试一试,感谢

**Comment by jakubiszon26** [comment]
on mine machine I have connected to Apple ID with no problem, but im using older ske EFI

**Comment by Chin-Me** [comment]
> 设有个黑苹果用户A，roll了三码为AAAAAAA，并官网校验为未激活设备，然后就开开心心的用了。
> 然后又有个黑苹果用户B，roll了三码碰巧roll出来的也是AAAAAAA，并官网校验为未激活设备，然后也开开心心的用了。
> 那么B的apple service就会被block。就算你校验了，到那时roll出了别人正在用的。这也有可能，尽管概率不大。
> 
> log out你的id。重roll一下四码。reset nvram。之后再osx里Factory reset。
> 我认为上述为缺一不可。

还请问一下Factory Reset应该不是重装系统吧,但是我在系统偏好设置中也没有找到相关的设置,请问具体该如何操作呢,已经重新摇过号了,nvram也重置了,现在就差出厂设置这一步

**Comment by ske1996** [comment]
> > 设有个黑苹果用户A，roll了三码为AAAAAAA，并官网校验为未激活设备，然后就开开心心的用了。
> > 然后又有个黑苹果用户B，roll了三码碰巧roll出来的也是AAAAAAA，并官网校验为未激活设备，然后也开开心心的用了。
> > 那么B的apple service就会被block。就算你校验了，到那时roll出了别人正在用的。这也有可能，尽管概率不大。
> > log out你的id。重roll一下四码。reset nvram。之后再osx里Factory reset。
> > 我认为上述为缺一不可。
> 
> 还请问一下Factory Reset应该不是重装系统吧,但是我在系统偏好设置中也没有找到相关的设置,请问具体该如何操作呢,已经重新摇过号了,nvram也重置了,现在就差出厂设置这一步,现在摇的新码还是用不了

按照苹果的流程执行Factory Reset

**Comment by Chin-Me** [comment]
> > > 设有个黑苹果用户A，roll了三码为AAAAAAA，并官网校验为未激活设备，然后就开开心心的用了。
> > > 然后又有个黑苹果用户B，roll了三码碰巧roll出来的也是AAAAAAA，并官网校验为未激活设备，然后也开开心心的用了。
> > > 那么B的apple service就会被block。就算你校验了，到那时roll出了别人正在用的。这也有可能，尽管概率不大。
> > > log out你的id。重roll一下四码。reset nvram。之后再osx里Factory reset。
> > > 我认为上述为缺一不可。
> > 
> > 
> > 还请问一下Factory Reset应该不是重装系统吧,但是我在系统偏好设置中也没有找到相关的设置,请问具体该如何操作呢,已经重新摇过号了,nvram也重置了,现在就差出厂设置这一步,现在摇的新码还是用不了
> 
> 按照苹果的流程进recovery执行Factory Reset

emm,我格盘重装也试过了,iMessage还是不正常,请问还有什么办法吗

**Comment by ske1996** [comment]
> > > > 设有个黑苹果用户A，roll了三码为AAAAAAA，并官网校验为未激活设备，然后就开开心心的用了。
> 
> > > > 然后又有个黑苹果用户B，roll了三码碰巧roll出来的也是AAAAAAA，并官网校验为未激活设备，然后也开开心心的用了。
> 
> > > > 那么B的apple service就会被block。就算你校验了，到那时roll出了别人正在用的。这也有可能，尽管概率不大。
> 
> > > > log out你的id。重roll一下四码。reset nvram。之后再osx里Factory reset。
> 
> > > > 我认为上述为缺一不可。
> 
> > > 
> 
> > > 
> 
> > > 还请问一下Factory Reset应该不是重装系统吧,但是我在系统偏好设置中也没有找到相关的设置,请问具体该如何操作呢,已经重新摇过号了,nvram也重置了,现在就差出厂设置这一步,现在摇的新码还是用不了
> 
> > 
> 
> > 按照苹果的流程进recovery执行Factory Reset
> 
> 
> 
> emm,我格盘重装也试过了,iMessage还是不正常,请问还有什么办法吗

那就是你的问题的，只能说你的格式化不彻底，这个问题我解决过太多了，都是这么做的，你怎么做的我也没看到，所以也没法说什么，只能告诉你，一定能弄好，具体的也没有现成的教程，我也懒得给你，太长，自己去好好看一下

**Comment by LiuLiujie** [comment]
这个问题和三码无关，是 apple id 被 ban 了，打电话给苹果客服
