### ISSUE TITLE
Matebook 14 2020（macOS、Win10、UOS）

### ISSUE THREAD

**Issue by jasonziai** [ske1996/matebook-13and14-OpenCore-Hackintosh#171]
Matebook 14 2020
CPU: Intel Core i5
RAM: 16G
SSD: LITEON 512G
Macos Version：Big Sur 11.5.2
EFI release Version: 20210508

Works fine:
感谢大佬的付出。功能基本跟描述一致，日常使用体验也接近白苹果
Doesnt work:
有30%左右的几率开机连不上Wi-Fi，关闭Wi-Fi再开启可以连上。不知道是不是个例。

**Comment by ske1996** [comment]
wifi的这个问题建议去/正常可用的部件/wifi   点击后展开详情去按我所写的去升级一下kext。

如果再有相同问题，建议去wifi kext的开发者那里提issue.
