### ISSUE TITLE
【Solved】升级正式Monterey失败

### ISSUE THREAD

**Issue by Eratty** [ske1996/matebook-13and14-OpenCore-Hackintosh#183]
Device info（设备信息）
Matebook 13 2019
CPU: i5 8265U
RAM: 8G
MacOS version: Big Sur11.6.1
EFI version:0.6.5

Describe the bug（问题简述）
目前是Big sur11.6.1，升级正式版Monterey时出现卡在无限循环进度条，配置文件中SecureBootmode也已经设为Disable。
求大佬帮忙解决，谢谢！

**Comment by ske1996** [comment]
把oc组件升级到0.7.5即可

**Comment by Eratty** [comment]
好的，感谢大佬

**Comment by Zhouxulin95** [comment]
兄弟，你升级成功了嘛

**Comment by Eratty** [comment]
> 兄弟，你升级成功了嘛

还没，上次没搞好。第二天要出差就没搞

**Comment by Zhouxulin95** [comment]
我OC升到0.7.5试了好些次，会直接识别不了12的安装盘，不知道是不是个例

**Comment by ske1996** [comment]
我自用的efi已经release了，有需要的自行下载，此issue关闭。
