### ISSUE TITLE
使用大神最新上传的oc0.7.5版本的EFI进行安装Monterey的时候，引导时报错Halting on critical error,请教下大神怎么解决

### ISSUE THREAD

**Issue by liutao-hue** [ske1996/matebook-13and14-OpenCore-Hackintosh#184]
Device info（设备信息）

Matebook 13 2019  

CPU:  i7-8565U
RAM:  Samsung H9CCNNNBJTALAR-NVD x2 8G
SSD model:Samsung SSD 970 EVO Plus 1TB
MacOS version:   macOS Monterey 12.0.1 21A559
EFI release version:0.7.5

Describe the bug（问题简述）
1、苹果小兵下载镜像
2、在大神的release下载的Just.for.Monterey.MB13.2018-2019.Oc0.7.5.7z最新的OC EFI引导。
3、正常替换OC引导EFI
4、重启电脑进入OC引导；注：我是用rEFInd引导选择OC引导进行OC引导界面启动
5、但进入引导时只报了Halting on critical error提示

Screenshots（截图）
![image](https://user-images.githubusercontent.com/75152458/140614509-e459213b-9d40-496b-b0c3-80a30245223d.png)

**Comment by ske1996** [comment]
去阅读repo内注意事项

**Comment by liutao-hue** [comment]
> 去阅读repo内注意事项

大神，我阅读过MUST readme，我是提前解锁了cfg 和修改dvmt至64mb，但启动的时候就是报这个
