### ISSUE TITLE
HDMI连接扩展屏（只是2k 60的屏）没有信号

### ISSUE THREAD

**Issue by clyz-mm** [ske1996/matebook-13and14-OpenCore-Hackintosh#188]
**Device info（设备信息）**

Matebook 14 2019  

CPU:  i5 8265U
RAM:  16G(升级过板载内存)
SSD model: SN720
MacOS version:   macOS Big Sur 11.6 20G165
EFI release version: Matebook.14.2018-2019.20210508

**Describe the bug（问题简述）**
HDMI连接扩展屏（只是2k 60的屏）没有信号，按alt键检测显示屏也检测不到，看了所有Issues ，只有一个类似的，里面回复中有一个
![image](https://user-images.githubusercontent.com/44491669/147449226-9bd49fc0-62fb-4260-8037-9c4493984037.png)
这个文件我下下来跟我的config比较，我的多了一个force-online的key，不知道是不是这个的问题，然后如果我改的话是要怎么改？在MacOS里面改config吗。

**To Reproduce（详述问题发生前的操作）**
无
**Screenshots（截图）**
![image](https://user-images.githubusercontent.com/44491669/147449542-66a2ee58-8635-4e6b-8e94-495b9a6946bd.png)

**Additional context（其他附件事项）**
无

**Comment by ske1996** [comment]
1. 其他什么都没动的对吗？
2. 能确定线和屏幕都没问题吗？别的系统下可以输出信号吗？
3. hdmi直连吗？
4. 你确定是没有信号还是有信号但是黑屏？有没有卡一下之类的，绿一下之类？
5. 按alt检测不出来屏幕什么意思？
6. 在偏好设置/显示器里怎么情况？给个截图

需要你回答上面每一个问题，一个不能少

**Comment by clyz-mm** [comment]
非常感谢大佬的回复！！！

第一个问题：只改了config.plist 里面的三码，改动如下：
![image](https://user-images.githubusercontent.com/44491669/147518410-dd0861f6-0496-4a13-9761-fb8e85e629b9.png)

第二个问题：线和屏幕肯定是没有问题的，日常都是用win+扩展屏办公的，现在也是用扩展屏回复大佬的。因为可以确定屏幕和线是没问题的，所以就没有换线，换屏。macos下热拔插过，除了macos会卡一会外，屏幕没有任何反应，还是无信号。

第三个问题：HDMI线是直连的，没有经过任务转换。

第四个问题：这个问题我试了两种情况：
1、开机启动macos前连接屏幕，启动后屏幕没有任何反应，无信号。
2、开机启动macos前不连接屏幕，启动后再插上屏幕，屏幕依旧显示无信号，但是macos会变卡，过一会又不卡了。
总之都是没有信号。

第五个问题：
看网上的教程，按alt右下角会显示“检测显示器”的按钮，但是我按了以后没有反应。具体如下图：
<img width="670" alt="截屏2021-12-28 上午9 29 59" src="https://user-images.githubusercontent.com/44491669/147519073-041580c5-9510-45a7-9cd7-01413bc29274.png">

第六个问题：
显示器里面是这样的：
<img width="1343" alt="截屏2021-12-28 上午9 34 23" src="https://user-images.githubusercontent.com/44491669/147519121-6d41d6fe-32fc-4f53-921f-bb50f80d1da4.png">
按大佬您的教程弄了HiDPi，显示很完美。
Hackintool里面的接口也没有读到外接屏。

补充：macos我是安装在移动硬盘（SSD）里的，这个应该没有什么影响吧

**Comment by clyz-mm** [comment]
> 1. 其他什么都没动的对吗？
> 2. 能确定线和屏幕都没问题吗？别的系统下可以输出信号吗？macos下控制变量法情况如何？换屏不换线，换线不换屏
> 3. hdmi直连吗？
> 4. 你确定是没有信号还是有信号但是黑屏？有没有卡一下之类的，绿一下之类？
> 5. 按alt检测不出来屏幕什么意思？
> 6. 接线后在偏好设置/显示器里怎么情况？给个截图
> 
> 需要你回答上面每一个问题，一个不能少

**Comment by clyz-mm** [comment]
> 

非常感谢大佬的回复！！！

第一个问题：只改了config.plist 里面的三码，改动如下：
image

第二个问题：线和屏幕肯定是没有问题的，日常都是用win+扩展屏办公的，现在也是用扩展屏回复大佬的。因为可以确定屏幕和线是没问题的，所以就没有换线，换屏。macos下热拔插过，除了macos会卡一会外，屏幕没有任何反应，还是无信号。

第三个问题：HDMI线是直连的，没有经过任务转换。

第四个问题：这个问题我试了两种情况：
1、开机启动macos前连接屏幕，启动后屏幕没有任何反应，无信号。
2、开机启动macos前不连接屏幕，启动后再插上屏幕，屏幕依旧显示无信号，但是macos会变卡，过一会又不卡了。
总之都是没有信号。

第五个问题：
看网上的教程，按alt右下角会显示“检测显示器”的按钮，但是我按了以后没有反应。具体如下图：
截屏2021-12-28 上午9 29 59

第六个问题：
显示器里面是这样的：
截屏2021-12-28 上午9 34 23
按大佬您的教程弄了HiDPi，显示很完美。
Hackintool里面的接口也没有读到外接屏。

补充：macos我是安装在移动硬盘（SSD）里的，这个应该没有什么影响吧

**Comment by clyz-mm** [comment]
> 1. 其他什么都没动的对吗？
> 2. 能确定线和屏幕都没问题吗？别的系统下可以输出信号吗？macos下控制变量法情况如何？换屏不换线，换线不换屏
> 3. hdmi直连吗？
> 4. 你确定是没有信号还是有信号但是黑屏？有没有卡一下之类的，绿一下之类？
> 5. 按alt检测不出来屏幕什么意思？
> 6. 接线后在偏好设置/显示器里怎么情况？给个截图
> 
> 需要你回答上面每一个问题，一个不能少

非常感谢大佬的回复！！！

第一个问题：只改了config.plist 里面的三码，改动如下：
![image](https://user-images.githubusercontent.com/44491669/147519799-e48d1b9a-72c4-4993-9d70-f2d606531656.png)

第二个问题：线和屏幕肯定是没有问题的，日常都是用win+扩展屏办公的，现在也是用扩展屏回复大佬的。因为可以确定屏幕和线是没问题的，所以就没有换线，换屏。macos下热拔插过，除了macos会卡一会外，屏幕没有任何反应，还是无信号。

第三个问题：HDMI线是直连的，没有经过任务转换。

第四个问题：这个问题我试了两种情况：
1、开机启动macos前连接屏幕，启动后屏幕没有任何反应，无信号。
2、开机启动macos前不连接屏幕，启动后再插上屏幕，屏幕依旧显示无信号，但是macos会变卡，过一会又不卡了。
总之都是没有信号。

第五个问题：
看网上的教程，按alt右下角会显示“检测显示器”的按钮，但是我按了以后没有反应。具体如下图：
<img width="670" alt="截屏2021-12-28 上午9 29 59" src="https://user-images.githubusercontent.com/44491669/147519831-d8f7b73b-beb4-40d5-b43d-2a040e29a4cc.png">

第六个问题：
显示器里面是这样的：
<img width="1343" alt="截屏2021-12-28 上午9 34 23" src="https://user-images.githubusercontent.com/44491669/147519858-928c199b-f128-433e-8666-66e416a95367.png">

按大佬您的教程弄了HiDPi，显示很完美。
Hackintool里面的接口也没有读到外接屏。

补充：macos我是安装在移动硬盘（SSD）里的，这个应该没有什么影响吧

**Comment by clyz-mm** [comment]
你好，我用军刀改了一下配置，现在外接屏可以用了，但是有个新的问题：外接屏开启hidpi后只能选择1920x1080的分辨率，非常模糊，选择别的分辨率就完全看不了，连比例都不正常了。不知道是不是我的外接屏开启的hidpi的方式不对，还是啥原因。想请教一下您。

<img width="1339" alt="截屏2021-12-28 下午2 40 29" src="https://user-images.githubusercontent.com/44491669/147536255-6d90baf6-9932-400a-8bde-d87883b579a5.png">

补充：外接屏开启hidpi的方式跟您的教程一样。外接屏分辨率：2560x1440。
期待您的回复

**Comment by ske1996** [comment]
> 你好，我用军刀改了一下配置，现在外接屏可以用了，但是有个新的问题：外接屏开启hidpi后只能选择1920x1080的分辨率，非常模糊，选择别的分辨率就完全看不了，连比例都不正常了。不知道是不是我的外接屏开启的hidpi的方式不对，还是啥原因。想请教一下您。
> 
> <img alt="截屏2021-12-28 下午2 40 29" width="1339" src="https://user-images.githubusercontent.com/44491669/147536255-6d90baf6-9932-400a-8bde-d87883b579a5.png">
> 
> 补充：外接屏开启hidpi的方式跟您的教程一样。外接屏分辨率：2560x1440。 期待您的回复

我的hidpi教程是针对内屏的。不要套用在外屏上。

外屏的比例确定一下应该不是三比二吧？是16比9对吗？

插上外屏后，用同一个hidpi的脚本你会发现最开始步骤会让你选屏幕，这里选你的外接屏，具体外接屏判别方法需要你自行判断。

选了外接屏后要根据你外接屏的比例和分辨率去做hipdi的配置，不可套用我写的内屏的教程。

**Comment by clyz-mm** [comment]
> > 你好，我用军刀改了一下配置，现在外接屏可以用了，但是有个新的问题：外接屏开启hidpi后只能选择1920x1080的分辨率，非常模糊，选择别的分辨率就完全看不了，连比例都不正常了。不知道是不是我的外接屏开启的hidpi的方式不对，还是啥原因。想请教一下您。
> > <img alt="截屏2021-12-28 下午2 40 29" width="1339" src="https://user-images.githubusercontent.com/44491669/147536255-6d90baf6-9932-400a-8bde-d87883b579a5.png">
> > 补充：外接屏开启hidpi的方式跟您的教程一样。外接屏分辨率：2560x1440。 期待您的回复
> 
> 我的hidpi教程是针对内屏的。不要套用在外屏上。
> 
> 外屏的比例确定一下应该不是三比二吧？是16比9对吗？
> 
> 插上外屏后，用同一个hidpi的脚本你会发现最开始步骤会让你选屏幕，这里选你的外接屏，具体外接屏判别方法需要你自行判断。
> 
> 选了外接屏后要根据你外接屏的比例和分辨率去做hipdi的配置，不可套用我写的内屏的教程。

是的，比例是16：9，那这个我应该怎么去配置具体的分辨率，直接配置2560x1440吗，或者说这个分辨率配置有那些方法和讲究，可以给个教程啥的，我去研究研究，感谢！

**Comment by ske1996** [comment]
具体的建议你百度搜索黑苹果hidpi 2k。
我手上没有现成教程。

另外看你问题解决了，此issue关闭哈

**Comment by clyz-mm** [comment]
> 具体的建议你百度搜索黑苹果hidpi 2k。 我手上没有现成教程。
> 
> 另外看你问题解决了，此issue关闭哈

好的，非常感谢大佬的efi！

**Comment by HanHan666666** [comment]
我今天试了一下刷新NVRAM，就能使用外接显示器了，希望对你有帮助。
