### ISSUE TITLE
大佬请问八代i7 2019款matebook13安装蒙特雷最后一直重装怎么解决啊

### ISSUE THREAD

**Issue by drbjsk** [ske1996/matebook-13and14-OpenCore-Hackintosh#189]
大佬你好，我用你发布的efi安装蒙特雷抹盘安装后，第二步重启的时候，它就一直重启然后就提示我要连接网络安装，这是怎么回事啊？我需要怎么解决这个问题呢？谢谢您的解答

**Comment by drbjsk** [comment]
Matebook
13 2019 CPU： i7-8565u
EFI 版本： But just for Matebook 13 2018-2019 ver.

第二遍重启大概还剩12分钟的时候，又重启然后再进来又要重新安装而且要联网

**Comment by ske1996** [comment]
你的信息没有提供全，按照bug report的格式提供全，不要偷懒。

你好，
没遇到过你说的这个…
但是感觉看起来像是你写的安装盘出问题了，
建议换个u盘，要大于16g，去重新写盘试一下。
我前天刚用一样的efi更新了最新的系统，没有出现问题。

**Comment by drbjsk** [comment]
那我再试试，可能我没改三码的原因
