### ISSUE TITLE
大神请问一下我写蒙特雷的u盘失败怎么回事呀

### ISSUE THREAD

**Issue by drbjsk** [ske1996/matebook-13and14-OpenCore-Hackintosh#190]
大神我闪迪64G的优盘用balenaEtcher写盘老是失败怎么回事呀？md5没有问题，不管写多少次都提示失败，怎么解决

**Comment by ske1996** [comment]
是校验失败不是写盘失败吧？

把你的'失败'的图发出来看看。

校验失败挺正常的，直接忽略就行。
