### ISSUE TITLE
Matebook13 2019 Monterey12.2 蓝牙无法启用

### ISSUE THREAD

**Issue by xth1227** [ske1996/matebook-13and14-OpenCore-Hackintosh#191]
**Device info（设备信息）**
Matebook 13 2019  
<img width="362" alt="截屏2022-02-11 下午11 57 20" src="https://user-images.githubusercontent.com/77375608/153624731-4d8efec3-05d1-4309-98af-59f3784a51c9.png">

CPU:  i7-8565U
RAM:  8G
SSD model:WD
MacOS version:   Monterey12.2
EFI release version:[Just.for.Monterey.MB13.2018-2019.Oc0.7.5.7z](https://github.com/ske1996/matebook-13and14-OpenCore-Hackintosh/releases/download/20210811/Just.for.Monterey.MB13.2018-2019.Oc0.7.5.7z)

**Describe the bug（问题简述）**
你好，首先很感谢楼主的帖子！我和楼主的电脑型号好像是一模一样的，之前按照楼主的帖子成功用上Big Sur好一段时间了，一点bug也没有，感谢楼主！
不过今天我忽然很想用Monterey，于是用楼主给的efi按照帖子操作一番，最后成功了，wifi正常，但是蓝牙显示关闭，怎么也启动不了（鼠标按了没有反应），希望楼主帮忙解决！
**To Reproduce（详述问题发生前的操作）**

**Screenshots（截图）**
<img width="362" alt="截屏2022-02-11 下午11 57 20" src="https://user-images.githubusercontent.com/77375608/153624821-94d0f0e2-1328-4831-b80f-e35b83bebb5b.png">

**Additional context（其他附件事项）**

**Comment by ske1996** [comment]
你好呀～

那个efi就是我自己用的，你就仅仅只改个三码就行了。

蓝牙驱动的加载在montery有一些小变动，所以你要是改了kext的加载相关的东西的话，你就要重新研究下我的config是怎么写的了。

下面的这个是作者z大官方的文档，已经给你定位到相关那一页了

https://openintelwireless.github.io/IntelBluetoothFirmware/Troubleshooting.html#identifying-issues

**Comment by xth1227** [comment]
> 你好呀～
> 
> 那个efi就是我自己用的，我一直用着都没问题，今天还刚OTA了12.2.1。你就仅仅只改个三码就行了。
> 
> 蓝牙驱动的加载在montery有一些小变动，所以你要是改了kext的加载相关的东西的话，你就要重新研究下我的config是怎么写的了。
> 
> 下面的这个是作者z大官方的文档，已经给你定位到相关那一页了
> 
> https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey

首先我特别高兴地通知楼主，问题解决了！！！
说来真是惭愧，原来是我在config中选择机型时选择错误（我选择了macbook16 13英寸版），刚才心血来潮（真的是心血来潮hh）换了个mac pro（就是那个大机箱），关机重新开机了一下，只听我的小爱同学一声“蓝牙已连接”，我就知道，蓝牙恢复了！
再次感谢楼主提供的链接以及亲切的回复！如果有时间的话可以解释一下这是为什么吗hhh
