### ISSUE TITLE
装黑苹果前后，oc引导每次进入电脑都会滴的响一下，声音很大

### ISSUE THREAD

**Issue by dreamay** [ske1996/matebook-13and14-OpenCore-Hackintosh#199]
Device info（设备信息）

Matebook 14 2019

CPU: Core i5-8265U 
RAM: 8G（三星LPDDR3 2133MHz)
SSD model:西数WDC PC SN720-512G
MacOS version: 10.15.6
EFI release version:matebook-13and14-OpenCore-Hackintosh

Describe the bug（问题简述）
装黑苹果前后，oc引导每次进入电脑都会滴的响一下，声音很大

To Reproduce（详述问题发生前的操作）

下载ske1996大神的Moterey12.3三驱动镜像
按照教程安装后，系统正常，每次oc引导电脑都会滴的响一下（无论是安装中还是安装后都会响），不是开机启动音。

请问大佬，这是怎么回事呢

**Comment by ske1996** [comment]
百度搜一下OC开机音就有设置教程了。
我设置的是苹果自己的开机音效。你的只会滴一声应该是你自己改我的做的设置改错了。
或者是你的EFI文件不全。

具体的自己去按照教程排查哈

**Comment by dreamay** [comment]
> 百度搜一下OC开机音就有设置教程了。 我设置的是苹果自己的开机音效。你的只会滴一声应该是你自己改我的做的设置改错了。 或者是你的EFI文件不全。
> 
> 具体的自己去按照教程排查哈

不是开机音呢，开机音我删掉还是有滴的一声，和设备出故障似的，但是能正常进系统，我没有修改efi，只修改了三码😣

**Comment by dreamay** [comment]
@ske1996 大佬，我用oc引导安装的系统，还可以用clover引导双系统吗

**Comment by ske1996** [comment]
可以考虑false掉showpicker并默认仅oc去引导macos，具体的我都在repo里写了
