### ISSUE TITLE
（delete all text and describe the bug）（删除这里所有文字并简述问题）

### ISSUE THREAD

**Issue by juxni6** [ske1996/matebook-13and14-OpenCore-Hackintosh#203]
你好up，首先感谢你的开发与分享，在使用的时候遇到一个问题，想向您请教，请检阅

CPU:  i7-10510U
RAM:  16
SSD model: NVME
MacOS version:   big sur 11.0.1
EFI release version:  matebook 14 2020 从你的releases里下载的

question describe：
我把从黑锅小兵的Big Sur镜像写到u盘然后替换你的efi启动，选择安装Big Sur后没有出现苹果的logo，出现的是禁止符号，请问这种情况该怎么办？
我插的usb3.0的口
^W^

**Comment by ske1996** [comment]
原因有很多，所以建议你自行百度并逐个排查。

这种比较泛泛的问题我很难解答
