### ISSUE TITLE
Matebook13 2019安装BigSur卡在剩余16分钟

### ISSUE THREAD

**Issue by ZemperWong** [ske1996/matebook-13and14-OpenCore-Hackintosh#205]
Matebook 13 2019  

CPU:  i5 8265u
RAM:  8GB
SSD model:三星512GB
MacOS version:  BigSur11.6.8
EFI release version:Matebook.13.2018-2019.20210811

作者你好，我使用的黑果小兵BigSur11.6.8，安装进度条卡在 剩余16分钟界面，鼠标不能动，机器卡死。后又尝试Bigsur11.2同样也是卡在剩余14分钟 都是进度条中间位置。跪求帮帮忙支支招。

**To Reproduce（问题发生前的操作）**
按照作者说的 关闭了bios的所有带安全的，关闭了windows启动项
efi的config也更改了四码，使用GenSMBIOS生成了MacBookPro15,2的

**Screenshots（截图）**
![微信图片_20220902144427](https://user-images.githubusercontent.com/61779624/188075190-37cd4911-ee2e-4782-b9eb-5f6184f6a656.jpg)

**Comment by ske1996** [comment]
你的ssd的具体型号是什么呀？

那个SSD model是用来写具体型号
