### ISSUE TITLE
MateBook13 WRT-WX9 (8265U) 无法正常与Monterey/Vertuna启动

### ISSUE THREAD

**Issue by cxgreat2014** [ske1996/matebook-13and14-OpenCore-Hackintosh#209]
**Device info（设备信息）**

MateBook13 WRT-WX9 (未在华为官网查到该型号确切年份，购置于2019年年初)

CPU:  Intel(R) Core(TM) i5-8265U CPU
RAM:  8GB
SSD model: WDC PC SN720 SDAPNTW-512G-1027
MacOS version:   Monterey 12.3
EFI release version: [Just.for.Monterey.MB13.2018-2019.Oc0.7.5.7z](https://github.com/ske1996/matebook-13and14-OpenCore-Hackintosh/releases/download/20210811/Just.for.Monterey.MB13.2018-2019.Oc0.7.5.7z)

**Describe the bug（问题简述）**

更改三码和device-id后放入引导分区启动，不断输出日志，无法正常进入安装页面。

**To Reproduce（详述问题发生前的操作）**
1. 按教程解锁cfg和dvmt 64m
2. 更改三码后直接放入EFI分区启动
3. 报错 `IOG Flags 0x3 (0x51)`
4. 查阅该报错代码和whatevergreen文档，在 
 https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-uhd-graphics-610-655-coffee-lake-and-comet-lake-processors 下找到 UHD 620 显卡需要设置 `device-id` 为 `A53E0000` ，遂进行相应更改并重新启动。
5. 不断的跑代码，不能进入UI界面。

**Screenshots（截图）**

![image](https://user-images.githubusercontent.com/15062548/200101530-87e9140c-ee18-4e29-ae3d-7ddb99acde96.png)

![image](https://user-images.githubusercontent.com/15062548/200101571-1f50a2f7-5d1f-482f-a99c-8abaef303a1c.png)

**Additional context（其他附件事项）**

**Comment by ske1996** [comment]
这个还真不能说是我的config的bug。  
哥们你这个是长得像matebook14还是13的那个企业版？
如果是长得像14的那个，就用14的efi文件包，如果是长得像13就用13的。我都在这种企业版上的测试过，都没问题。
另外你改的那个```device-id```是叫属于做“缓冲帧”的设置部分，真要改也不是只改一个id就完了。网上的缓冲帧定制的教程很多。这里就不展开讲了。  
此外，我设置的那个仿冒的```device-id```没有问题，可以用的，uhd620来说那两个id都可以。  我的那个efi不用改的。
另外我想知道，你没改我的efi之前有报错吗还是什么？应该能进系统的。

**Comment by cxgreat2014** [comment]
找到问题所在了。。

改好cfg和dvmt 64m之后重装过一遍windows，两个配置项被复原了

。。。。。。。


浪费时间：35小时+，谢谢你啊，Windows

**Comment by cxgreat2014** [comment]
附注，确实不用改device-id，谢谢大大

**Comment by cxgreat2014** [comment]
不好意思，刚刚升级到Vertuna，IOG Flags 0x3 (0x51)的问题又出现了。

![IMG_20221105_192657](https://user-images.githubusercontent.com/15062548/200117828-41371406-4020-40c8-86b5-ccad9c9c83f9.jpg)

**Comment by silentwsl** [comment]
> 不好意思，刚刚升级到Vertuna，IOG Flags 0x3 （0x51）的问题又出现了。
> 
> ![IMG_20221105_192657](https://user-images.githubusercontent.com/15062548/200117828-41371406-4020-40c8-86b5-ccad9c9c83f9.jpg)

利用OCAT把引导升级到最新版，然后CleanNvram试一下

**Comment by ske1996** [comment]
升级oc和所有kext到最新就行了。

我已经用了ventura有一段时间了。efi中的参数和acpi没有做调整。
